# Generated by Django 5.0.1 on 2024-04-06 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0006_contractorprofile_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('description', models.CharField(max_length=4000)),
                ('required', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('salary', models.PositiveIntegerField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.contractorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('description', models.CharField(max_length=4000)),
                ('required', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('salary', models.PositiveIntegerField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.companyprofile')),
            ],
        ),
    ]
