# Generated by Django 5.0.1 on 2024-03-30 12:15

import datetime
import django.core.validators
import resume.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Birth date cannot be earlier than 1900-01-01'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2006, 4, 4), message='You must be at least 18 years old')]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), resume.validators.validate_file_size]),
        ),
    ]
