# Generated by Django 5.0.1 on 2024-03-30 18:13

import django.core.validators
import resume.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_birth_date_alter_resume_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), resume.validators.validate_file_size]),
        ),
    ]
