# Generated by Django 5.0.1 on 2024-04-04 06:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resume_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(1900, 1, 1), message='Birth date cannot be earlier than 1900-01-01'), django.core.validators.MaxValueValidator(limit_value=datetime.date(2006, 4, 9), message='You must be at least 18 years old')]),
        ),
    ]
