# Generated by Django 5.0.1 on 2024-04-04 06:14

import django.core.validators
import django.db.models.deletion
import profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company_logo', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png']), profiles.validators.size_validator])),
                ('established_date', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('license_image', models.ImageField(upload_to='company_license', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png']), profiles.validators.size_validator])),
                ('company_email', models.EmailField(max_length=100)),
                ('company_website', models.URLField(max_length=100)),
                ('company_detail', models.TextField(max_length=10000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='company_logo', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png']), profiles.validators.size_validator])),
                ('address', models.CharField(max_length=300)),
                ('personal_email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
