# Generated by Django 5.0.1 on 2024-04-04 08:25

import django.core.validators
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='license_image',
            field=models.ImageField(upload_to='company_license', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg']), profiles.validators.size_validator]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(upload_to='company_logo', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg']), profiles.validators.size_validator]),
        ),
    ]
