# Generated by Django 5.0.1 on 2024-04-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_companyprofile_license_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='license_image',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo',
        ),
    ]
