# Generated by Django 5.0.1 on 2024-04-05 11:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_companyprofile_license_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_slug', message='Slug must be a positive integer value', regex='^[1-9]\\d*$')]),
            preserve_default=False,
        ),
    ]
